language: go
sudo: false
go:
  - 1.11.x
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/certok-darwin-amd64
          - cross/certok-darwin-amd64.md5
          - cross/certok-darwin-amd64.sha256
          - cross/certok-darwin-386
          - cross/certok-darwin-386.md5
          - cross/certok-darwin-386.sha256
          - cross/certok-freebsd-amd64
          - cross/certok-freebsd-amd64.md5
          - cross/certok-freebsd-amd64.sha256
          - cross/certok-freebsd-386
          - cross/certok-freebsd-386.md5
          - cross/certok-freebsd-386.sha256
          - cross/certok-linux-arm
          - cross/certok-linux-arm.md5
          - cross/certok-linux-arm.sha256
          - cross/certok-linux-arm64
          - cross/certok-linux-arm64.md5
          - cross/certok-linux-arm64.sha256
          - cross/certok-linux-amd64
          - cross/certok-linux-amd64.md5
          - cross/certok-linux-amd64.sha256
          - cross/certok-linux-386
          - cross/certok-linux-386.md5
          - cross/certok-linux-386.sha256
          - cross/certok-solaris-amd64
          - cross/certok-solaris-amd64.md5
          - cross/certok-solaris-amd64.sha256
          - cross/certok-windows-amd64
          - cross/certok-windows-amd64.md5
          - cross/certok-windows-amd64.sha256
          - cross/certok-windows-386
          - cross/certok-windows-386.md5
          - cross/certok-windows-386.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "xKTYeYDEszIS57wkjWtSWwLpEBwmVNZATDkelDIqD4iWOJfWQo6rKKmMsQezSObX0F0mchGa0H9CV2VAdWxOo9zrE5mhJIHJo8QHVya8ja4OeqGDBZK+N6SkZHENulQfzTVN1d7enY6/G5mbb8pPYnOgTlLnihqN4NR3+7VmOqV2oc6jGZ+pfwpMmhmKExAHIiKC9Lk+KuDsN9fitdTyejU4FzhF7I7Lg27R8JMO8RJ/zif3aipSUfbMXSFhfX9oqiOUgS9h2CzfXe2RiuXNejdehFiTGbo/dwXrXb2WpIRj1OieWxzUB7S+fe+FvmG4JxG/6/XcHAF7PiCElXoNWmTtoAgnMbfekTQnNMN4Vcln89PDfMWsJcr6XL3CrkrFoQJUrYo6oXcpxAyW6GXhBX8KqEXtVDOcA9jV4B2G9LpFFMp/OabSD/9GvyWNsQ8DfMKF/OK+8KzR5btiyorohKXAuRybURF3xcSHT1QJznAJgrZYX64ukJGx2mBWdaWeuRtljHoiJ6MohKdCZJk5ffNzFxhxOwfk+sRPaWAA1/WRVqhLQP2yT48D9EYjf5kYRL5YUZ5SpiJ8Wn+lZHmR33/QBOFBoynQyeS4nBFPbwZDHPxEhKQM8VAuKFKHzolCzfmZKoH4/G5y1IRiBSL+NS/kCLd7awEqxulSKGUbcr0="
